---
roles:
  # Install a role from Ansible Galaxy.
  - name: mullholland.repository_powertools
  # - name: mullholland.repository_codereadybuilder
  - name: mullholland.repository_epel
  - name: mullholland.repository_rpmfusion
