---
- name: remi | Include distribution specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}.yml'
    - '{{ ansible_system }}.yml'
    - 'default.yml'

- name: remi | Importing key
  ansible.builtin.rpm_key:
    key: "{{ item }}"
    state: present
  register: result
  until: result is succeeded
  retries: 5
  delay: 10
  with_items:
    - "{{ repository_remi_key[ansible_distribution][ansible_distribution_major_version] }}"

- name: remi | Install REMI Repository
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ repository_remi_package[ansible_distribution][ansible_distribution_major_version] }}"

- name: "remi | Enable REMI Repository"
  community.general.ini_file:
    path: "/etc/yum.repos.d/remi.repo"
    section: "remi"
    option: enabled
    value: "1"
    no_extra_spaces: true
    mode: "0644"
    create: false

# See: https://github.com/ansible/ansible/issues/64852
- name: "remi | RedHat/CentOS 8 | RedHat/CentOS 8 Switch (https://github.com/ansible/ansible/issues/64852)"
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version | int >= 8
  block:
    - name: remi | Ensure dnf-plugins are installed on CentOS 8+.
      ansible.builtin.yum:
        name: dnf-plugins-core
        state: present

    - name: remi | Enable DNF module for CentOS 8+.
      ansible.builtin.shell: |
        dnf module reset php
        dnf module enable -y php:remi-{{ repository_remi_php_version }}
      register: dnf_module_enable
      changed_when: "'Nothing to do' not in dnf_module_enable.stdout"
