---
molecule_exceptions:
  - variation: "Ubuntu*"
    reason: "repo only supports RedHat/CentOS Server"
  - variation: "Debian*"
    reason: "repo only supports RedHat/CentOS Server"
  - variation: "centos-stream9"
    reason: "FROm REMI WARNING: CentOS 9 is a development version, not ready for production."
molecule_scenarios:
  - scenario: "default"
    ansible: ["previous", "current", "next"]
    platforms:
      - "centos7"
      - "centos-stream8"
      - "ubi8"
      - "fedora34"
      - "fedora35"
      - "amazonlinux"
      - "rockylinux8"
      - "almalinux8"
