---
repository_remi_package:
  RedHat:
    "7":
      - "https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-7.noarch.rpm"
    "8":
      - "https://rpms.remirepo.net/enterprise/remi-release-8.rpm"
  CentOS:
    "7":
      - "https://rpms.remirepo.net/enterprise/remi-release-7.rpm"
    "8":
      - "https://rpms.remirepo.net/enterprise/remi-release-8.rpm"
    "9":
      - "https://rpms.remirepo.net/enterprise/remi-release-9.rpm"
    "10":
      - "https://rpms.remirepo.net/enterprise/remi-release-10.rpm"
  Rocky:
    "8":
      - "https://rpms.remirepo.net/enterprise/remi-release-8.rpm"
    "9":
      - "https://rpms.remirepo.net/enterprise/remi-release-9.rpm"
    "10":
      - "https://rpms.remirepo.net/enterprise/remi-release-10.rpm"
  AlmaLinux:
    "8":
      - "https://rpms.remirepo.net/enterprise/remi-release-8.rpm"
    "9":
      - "https://rpms.remirepo.net/enterprise/remi-release-9.rpm"
    "10":
      - "https://rpms.remirepo.net/enterprise/remi-release-10.rpm"
  Fedora:
    "42":
      - "https://rpms.remirepo.net/fedora/remi-release-42.rpm"
    "43":
      - "https://rpms.remirepo.net/fedora/remi-release-43.rpm"

repository_remi_key:
  RedHat:
    "7":
      - "https://rpms.remirepo.net/RPM-GPG-KEY-remi"
    "8":
      - "https://rpms.remirepo.net/RPM-GPG-KEY-remi2018"
  CentOS:
    "7":
      - "https://rpms.remirepo.net/RPM-GPG-KEY-remi"
    "8":
      - "https://rpms.remirepo.net/RPM-GPG-KEY-remi2018"
    "9":
      - "https://rpms.remirepo.net/RPM-GPG-KEY-remi2021"
    "10":
      - "https://rpms.remirepo.net/RPM-GPG-KEY-remi2024"
  Rocky:
    "8":
      - "https://rpms.remirepo.net/RPM-GPG-KEY-remi2018"
    "9":
      - "https://rpms.remirepo.net/RPM-GPG-KEY-remi2021"
    "10":
      - "https://rpms.remirepo.net/RPM-GPG-KEY-remi2024"
  AlmaLinux:
    "8":
      - "https://rpms.remirepo.net/RPM-GPG-KEY-remi2018"
    "9":
      - "https://rpms.remirepo.net/RPM-GPG-KEY-remi2021"
    "10":
      - "https://rpms.remirepo.net/RPM-GPG-KEY-remi2024"
  Fedora:
    "42":
      - "https://rpms.remirepo.net/RPM-GPG-KEY-remi2025"
    "43":
      - "https://rpms.remirepo.net/RPM-GPG-KEY-remi2025"
