---
repository_remi_package:
  RedHat:
    "7":
      - "https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-7.noarch.rpm"
    "8":
      - "https://rpms.remirepo.net/enterprise/remi-release-8.rpm"
  CentOS:
    "7":
      - "https://rpms.remirepo.net/enterprise/remi-release-7.rpm"
    "8":
      - "https://rpms.remirepo.net/enterprise/remi-release-8.rpm"
    "9":
      - "https://rpms.remirepo.net/enterprise/remi-release-9.rpm"
  Rocky:
    "8":
      - "https://rpms.remirepo.net/enterprise/remi-release-8.rpm"
  AlmaLinux:
    "8":
      - "https://rpms.remirepo.net/enterprise/remi-release-8.rpm"
  Amazon:
    "2":
      - "https://rpms.remirepo.net/enterprise/remi-release-7.rpm"
  Fedora:
    "33":
      - "https://rpms.remirepo.net/fedora/remi-release-33.rpm"
    "34":
      - "https://rpms.remirepo.net/fedora/remi-release-34.rpm"
    "35":
      - "https://rpms.remirepo.net/fedora/remi-release-35.rpm"

repository_remi_key:
  RedHat:
    "7":
      - "https://rpms.remirepo.net/RPM-GPG-KEY-remi"
    "8":
      - "https://rpms.remirepo.net/RPM-GPG-KEY-remi2018"
  CentOS:
    "7":
      - "https://rpms.remirepo.net/RPM-GPG-KEY-remi"
    "8":
      - "https://rpms.remirepo.net/RPM-GPG-KEY-remi2018"
  Rocky:
    "8":
      - "https://rpms.remirepo.net/RPM-GPG-KEY-remi2018"
  AlmaLinux:
    "8":
      - "https://rpms.remirepo.net/RPM-GPG-KEY-remi2018"
  Amazon:
    "2":
      - "https://rpms.remirepo.net/RPM-GPG-KEY-remi"
  Fedora:
    "33":
      - "https://rpms.remirepo.net/RPM-GPG-KEY-remi2020"
    "34":
      - "https://rpms.remirepo.net/RPM-GPG-KEY-remi2021"
    "35":
      - "https://rpms.remirepo.net/RPM-GPG-KEY-remi2021"
