---
- name: Verify
  hosts: all
  become: true
  gather_facts: true
  vars:
    molecule_repo_file: "remi.repo"
    molecule_repo_name: "remi"
    molecule_repo_packages:
      - "base58"
      - "php"
      # RedHat:
      #   "7":
      #     - "https://rpms.remirepo.net/RPM-GPG-KEY-remi"
      #   "8":
      #     - "https://rpms.remirepo.net/RPM-GPG-KEY-remi2018"
      # CentOS:
      #   "7":
      #     - "https://rpms.remirepo.net/RPM-GPG-KEY-remi"
      #   "8":
      #     - "https://rpms.remirepo.net/RPM-GPG-KEY-remi2018"
      # Rocky:
      #   "8":
      #     - "https://rpms.remirepo.net/RPM-GPG-KEY-remi2018"
      # AlmaLinux:
      #   "8":
      #     - "https://rpms.remirepo.net/RPM-GPG-KEY-remi2018"
      # Amazon:
      #   "2":
      #     - "https://rpms.remirepo.net/RPM-GPG-KEY-remi"
      # Fedora:
      #   "33":
      #     - "base58"
      #   "34":
      #     - "https://rpms.remirepo.net/RPM-GPG-KEY-remi2021"
      #   "35":
      #     - "https://rpms.remirepo.net/RPM-GPG-KEY-remi2021"

  tasks:
    - name: SmokeTests
      debug:
        msg:
          - "ansible_version => {{ansible_version}}"
          - "ansible_distribution => {{ ansible_distribution }}"
          - "ansible_distribution_major_version => {{ ansible_distribution_major_version }}"
          - "ansible_os_family  => {{ ansible_os_family}}"
          - "ansible_system  => {{ ansible_system }}"

    - name: "Test if repository exists and is enabled"
      community.general.ini_file:
        path: "/etc/yum.repos.d/{{ molecule_repo_file }}"
        section: "{{ molecule_repo_name }}"
        option: enabled
        value: "1"
        no_extra_spaces: true
        mode: "0644"
      register: molecule_repository_free
      failed_when: (molecule_repository_free is changed) or (molecule_repository_free is failed)

    - name: Check packages are installable from repository
      ansible.builtin.yum:
        name: "{{ molecule_repo_packages }}"
        state: present

    - name: Verify php version.
      shell: php --version
      args:
        warn: false
      register: molecule_php_version
      changed_when: "'PHP 8.1' not in molecule_php_version.stdout"
